kind: Secret
apiVersion: v1
metadata:
    name: wishlist-api-secrets
    namespace: staging-apps
stringData:
    NODE_ENV: ENC[AES256_GCM,data:cpi7QnIpoQ==,iv:QxoWg1JzuPC3/cyDACwhXDUNY9slU9r2VxopUn8Lp9Y=,tag:gyQLiiXehLCO/moGDF9X1g==,type:str]
    NODE_PORT: ENC[AES256_GCM,data:laSt6g==,iv:q7fvE3eVbsRvO1+q1+OOyzNOziV8hnIUBjeEa2AORKE=,tag:7EAd0rKO9ewO29jpzRECRQ==,type:str]
    NODE_HOST: ENC[AES256_GCM,data:LmfW4PvLzw==,iv:fi2/HPBr211BFt2yi+Fx05kUJhyQ0Ikfl22o64ugcxM=,tag:UrK5fn2rjowfMC7vvKlzgg==,type:str]
    APY_KEYS: ENC[AES256_GCM,data:4WmZeJY=,iv:sCYWhfHuxepCoabYE685xaOlXmlnRYtysOCDwAaHtSE=,tag:fnXthOIbCIpTNRVPtaAU3Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:mcQv4n0=,iv:tR2e9ovLHGYsk8RJ3io90yR2+c64eS6DpUTUR38p+vM=,tag:AUiAoQN7MOQmzxupNmjYtg==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:AG9hhlo=,iv:idJf+T1OdpaYvJnOMdQFmBinrwFbkOq11P6lknkjLFI=,tag:1SkyGlZ6mQd8ChuP50M80w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tc36u5lar3d9m0d6yqwzvrqq8vxgfe3zecnjewmytr22rr9qeazss239cg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybTUwZ0ltVFpMRlNXazZC
            MlRZSGRNbXJidzFIOWdDU1IxQlVsTldjbmtrCi9tWjl6a1VEdnpXajFDZmJyTmhS
            ckVWYWpqU25KSlZRVFNjZVd1Q2lxQjAKLS0tIDlweXhKbTAxV3NpOXlRZXZJMC90
            bTEyTi9OQTlwMlRwdmVZNGJYYTVCWW8K+YglajtPYE3a/e72sWZgBrFtse60Bw+y
            QPtVk+GB6AG3s6lLOjDabSckdjKeivnxUqAY25rFe9ItAfeWdluP9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T13:52:55Z"
    mac: ENC[AES256_GCM,data:3YqZbb7xhLQ9Q0QBA0sXTn91C5pme9SO1Es6JDU1etk+BlHmqhSN5qmJXYcGWxPSfupLZY7PCnP6KsQNHWkrEbTSIIbs9oCJvrxybiT1zJgcA/RrYyp1bjpHTTvTpeI1e5ppfZ2/9FTMDxtUMtV6+XwwOYJaOqoCc5AIKP2xJL0=,iv:ePB3K0zFOVUU1rtup8ktVcv4t0UCUeqtW/J9Y4vFNSk=,tag:2HxR/LmaQgHOmmaLDGLYmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
