kind: Secret
apiVersion: v1
metadata:
    name: wishlist-api-secrets
    namespace: production-apps
stringData:
    NODE_ENV: ENC[AES256_GCM,data:DKNfJeObinyE0w==,iv:Lv8nFUlNoooPc+aji1g3ZfOgyPdE5DikJfC2r9WNh5Q=,tag:InqdTzG59lriudd+qbEICw==,type:str]
    NODE_PORT: ENC[AES256_GCM,data:RrPlsw==,iv:+S2bMVtcA4CyoVP9SBdjM7GujLeZDVGEWzozF2UdBQk=,tag:QAIEQbOsw3m3ZSrdxKdUeA==,type:str]
    NODE_HOST: ENC[AES256_GCM,data:65RtIuA+MA==,iv:XEk8LTwZP5HPNbwM7J7upvR40bekf7ySKZ7htAUlUKU=,tag:+Yxlv+Hj90XH6qJ/fehQSw==,type:str]
    APY_KEYS: ENC[AES256_GCM,data:xDPtBEk=,iv:6WPwexn8/98jxK7R+oUPuFHMaLyRRHCjnbL/bFo2yJk=,tag:RSThrNdJyD4PKau+EZaTBw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:jNW3pWA=,iv:TeWxcjEJrYEJhdl3eWRUJWRhqHx8taEEsSnmwDmekl4=,tag:Qme9P09Ao5H/2dsJ5ujsIQ==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:zZIm1HE=,iv:vtoN7OAWgfPyPz4lon1R4f56y96Lck3JaW1aOIU2PxA=,tag:Ywsijgg+8MV6cepfdHuOQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tc36u5lar3d9m0d6yqwzvrqq8vxgfe3zecnjewmytr22rr9qeazss239cg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWHY3ZkdoeEkycExaeW8z
            djJwYVpuSXZuK2x3L05CL3pYejZ4bUExYjB3ClBsa1c4NENJNHczcUpGN2U0QSs2
            dDZpY1pmdEh5VU5sbUwxczN6Z1FiNXcKLS0tIE9Pc040ODBZS25FZDh6TFA5OTQ2
            Q3k1bnlJWmorNjZoMDVEd3g4M2h0MTAKdAYatq/BD74lnYFOKCTcEHyRKbze8Hpj
            eaac586vuTFlym6bx7/D+w+2Vjiw3v+9TfNT1c3rIWQ1kB5mmMQ4+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T13:57:14Z"
    mac: ENC[AES256_GCM,data:XLi3fe4JDhCXpVF9xqCgsUk1quhuvSpjxCgsjA970D14bP0s0wyEQ2ezRPwBFz5IIxjJEI2p2X6nLz2GXP/8S4ZVeoiCIoXEhqGTjiahIJZ3WZF2Q7fZBILuLkmKoxrSZREcdfHOO2toZ+KvUqQ5jWBVBzHtQTxOAv2N30PL6VY=,iv:24+2/PdvAjzX1iOPgcN9FxeX1h4DtgKndLXuY+jGm/s=,tag:l8TmCnLFrtXN2Bl7I82jxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
