kind: Deployment
apiVersion: apps/v1
metadata:
  name: wishlist-api-deployment
  namespace: staging-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-api
  template:
    metadata:
      labels:
        app: wishlist-api
    spec:
      containers:
        - name: wishlist-api
          image: docker.io/rempeloliveira/public:wishlist-api.0.0.1-staging
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: wishlist-api-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
